### PR TITLE
fix: migrated to flutter v2 and adding new screens

### PR DESCRIPTION
**Pull request by rishavnaskar**
### Fixes

- [x] Migrated the project to support latest Flutter Null Safety
- [x] Modified most of the code which needed to be changed as many classes were deprecated, did not support null safety and had overflow issues and some bugs.
- [x] Added Missing files and packages. Some of the code was reused from other repositories but were not included in the project. So had to include them as well

### New features

- [x] Working on a newly set of pages based on Google Maps

### CODE REVIEW

**Comment by samarthagarwal** [comment]
Hi @rishavnaskar. Thank you for your contributions. I would just like to point out one thing. The FlutterScreens repo should have also custom-written code so I avoid any external packages. I have removed the landing page that used an external package. I want to have these widgets as drop-in solutions with 0 deps. Hope that makes sense.

**Comment by rishavnaskar** [comment]
> Hi @rishavnaskar. Thank you for your contributions. I would just like to point out one thing. The FlutterScreens repo should have also custom-written code so I avoid any external packages. I have removed the landing page that used an external package. I want to have these widgets as drop-in solutions with 0 deps. Hope that makes sense.

Hey @samarthagarwal, I just found out this a couple of days ago and I just love this repo. 
I totally understand about the 0 deps part. I had the same idea too. But then while fixing bugs, I found packages like *CachedNetworkImage* have been used but their code was not copied, neither were the respective packages included. So I thought of including the same so as to make it work. But now that you have removed them, I will take a pull.

Also, I was hoping to work on a **Google Maps UI** with some major enhancements, which often people use a lot. But that would not be possible without including the *googlemaps* package. Would you allow me to include just that package? I am asking because a lot of people work with Google Maps on Flutter and without that package, working with the same is not possible to my knowledge.

**Comment by samarthagarwal** [comment]
I understand. For these kinds of widgets, we can start a different repo with most common features and widgets with common functionalities built-in.

**Comment by rishavnaskar** [comment]
> I understand. For these kinds of widgets, we can start a different repo with most common features and widgets with common functionalities built-in.

Okay, I see your point. I guess a different repo would be more appropriate.

**Pull request merged**
